### ISSUE TITLE
sign up form issue on new build

### ISSUE THREAD

**Issue by amiresfahani** [pomozoff/caspianphone#95]
sign up form is not loading list of countries and is cutted

**Comment by pomozoff** [comment]
When is no internet connection is present the app can't retrieve that list.
We have two ways to fix this issue.

First one is to store countries list inside the app.
Pro - no internet connection is needed to display this list.
Con - to update the list we need to build and publish a new app to the AppStore.

Second way is to check when the internet connection is back again and try to retrieve the countries list again.
Pro - no need to change the app if the countries list needs to be changed.
Con - still need the internet to retrieve and display the list.

I think the second way is better, because a user should register online, and no need to change the app if the list has been changed.

**Comment by pomozoff** [comment]
I added waiting view until countries list is not loaded
